version: '3.8'

services:
  deleuze-auth-db:
    image: 871950640338.dkr.ecr.ap-northeast-1.amazonaws.com/deleuze-db:16-alpine
    container_name: deleuze-auth-db
    ports:
      - "${AUTH_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    command: ["-c", "log_statement=all"]
    volumes:
      - deleuze_auth_db_data:/var/lib/postgresql/data

  deleuze-mng-db:
    image: 871950640338.dkr.ecr.ap-northeast-1.amazonaws.com/deleuze-db:16-alpine
    container_name: deleuze-mng-db
    ports:
      - "${MNG_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${MNG_DB_NAME}
    command: ["-c", "log_statement=all"]
    volumes:
      - deleuze_mng_db_data:/var/lib/postgresql/data

  deleuze-drive-db:
    image: 871950640338.dkr.ecr.ap-northeast-1.amazonaws.com/deleuze-drive-db:16-alpine
    container_name: deleuze-drive-db
    ports:
      - "${DRIVE_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DRIVE_DB_NAME}
    command: ["-c", "log_statement=all"]
    volumes:
      - deleuze_drive_db_data:/var/lib/postgresql/data

volumes:
  deleuze_auth_db_data:
  deleuze_mng_db_data:
  deleuze_drive_db_data: