CREATE TABLE IF NOT EXISTS "Users"
(
    "Id" SERIAL PRIMARY KEY,
    "LoginId" VARCHAR(100) NOT NULL UNIQUE,
    "PasswordHash" VARCHAR(255) NOT NULL,
    "TenantId" VARCHAR(100) NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "IX_Users_TenantId"
ON "Users" ("TenantId");