name: CI Build Check

on:
  push:
    branches: [ deleuze-api-v2.0 ]
    paths:
      - 'deleuze-auth/**'
      - 'deleuze-app/**'
      - 'deleuze-mng/**'
      - 'deleuze-drive/**'
      - 'deleuze-shared/**
      - '.github/workflows/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      auth:  ${{ steps.filter.outputs.auth }}
      app:   ${{ steps.filter.outputs.app }}
      mng:   ${{ steps.filter.outputs.mng }}
      drive: ${{ steps.filter.outputs.drive }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          auth:  ['deleuze-auth/**']
          app:   ['deleuze-app/**']
          mng:   ['deleuze-mng/**']
          drive: ['deleuze-drive/**']

  build-check:
    needs: changes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # deleuze-auth のビルドチェック
    - name: Build check deleuze-auth
      if: ${{ needs.changes.outputs.auth == 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: ./deleuze-auth
        platforms: linux/amd64
        push: false # ECR にプッシュせずビルド成否のみ検証

    # deleuze-app のビルドチェック
    - name: Build check deleuze-app
      #if: ${{ needs.changes.outputs.app == 'true' }}
      if false
      uses: docker/build-push-action@v5
      with:
        context: ./deleuze-app
        platforms: linux/amd64
        push: false

    # deleuze-mng のビルドチェック
    - name: Build check deleuze-mng
      # if: ${{ needs.changes.outputs.mng == 'true' }}
      if false
      uses: docker/build-push-action@v5
      with:
        context: ./deleuze-mng
        platforms: linux/amd64
        push: false

    # deleuze-drive のビルドチェック
    - name: Build check deleuze-drive
      # if: ${{ needs.changes.outputs.drive == 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: ./deleuze-drive
        platforms: linux/amd64
        push: false