<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Deleuze.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- ASP.NET Core の共通機能（HttpContext, Authenticationハンドラー等）を利用可能にする -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <!-- JWT Bearer 認証機能用パッケージ -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
  </ItemGroup>

</Project>